# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
import numpy as np
print(np.__version__)

1.21.4


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [4]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [6]:
x = np.array([100,20,34])
print(x.size)
print(x.itemsize) # find size of one element

3
4


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [7]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [14]:

x= np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [18]:
x = np.arange(10,50,1)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [19]:
x = np.arange(10,50,1)
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [27]:
x = np.arange(0,9,1).reshape(3,3)
#x.reshape(3)
print(x)
print(x.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [31]:
x= np.array([1, 2, 0,0,4,0])
print(x)
np.nonzero(x)

[1 2 0 0 4 0]


(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [32]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [33]:
x = np.random.random((3,3,3))
print(x)

[[[0.20410238 0.09361588 0.15123539]
  [0.33051756 0.8261607  0.63716312]
  [0.13891229 0.97458179 0.73482411]]

 [[0.77918439 0.6802271  0.02507398]
  [0.53772215 0.8350015  0.64144218]
  [0.22846392 0.83225616 0.92855235]]

 [[0.89249981 0.50185129 0.55253738]
  [0.59060699 0.85148325 0.48774379]
  [0.51439394 0.78291294 0.83327537]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [35]:
x = np.random.random((10,10))
print(x)
print(np.max(x))
print(np.min(x))

[[0.66771937 0.20324711 0.12840683 0.10323919 0.2653806  0.59778626
  0.77377488 0.10130552 0.66477579 0.60706404]
 [0.39424869 0.41917196 0.27021538 0.19160899 0.64191246 0.37714506
  0.10304688 0.11132936 0.02467018 0.68658058]
 [0.31418408 0.30246427 0.57676126 0.47112833 0.77664286 0.11806629
  0.09788065 0.82920885 0.3796758  0.05344207]
 [0.12100724 0.81069384 0.75533963 0.13913414 0.40899912 0.03179428
  0.68689269 0.32497947 0.94499713 0.77784657]
 [0.07043995 0.20007652 0.93734562 0.17726248 0.01607598 0.34302417
  0.15087077 0.51492896 0.89312026 0.00472591]
 [0.37639756 0.21955082 0.47010536 0.96375754 0.71773109 0.86522035
  0.06790742 0.79794487 0.3904293  0.88158501]
 [0.35742509 0.30448119 0.73894723 0.955299   0.85815474 0.29756229
  0.3082854  0.63489485 0.46776255 0.42683207]
 [0.76720099 0.37466845 0.81720052 0.38871336 0.48292422 0.52890217
  0.07020885 0.98441316 0.67266795 0.727945  ]
 [0.7129968  0.99318905 0.36454237 0.67011852 0.25926252 0.71468054
  0.71822134

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [37]:
x = np.random.random(30)
print(x)
print(np.mean(x))


[0.17877333 0.03726146 0.80593513 0.28114668 0.91585432 0.6485346
 0.03806811 0.58617181 0.32444011 0.45692247 0.69387286 0.15610717
 0.65490166 0.90031821 0.35962888 0.43142046 0.41308759 0.91812266
 0.47353671 0.52116629 0.10482132 0.79657523 0.73368487 0.37530472
 0.17562749 0.73257179 0.82240683 0.39006164 0.27049006 0.11052951]
0.4769114653904623


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [42]:
x = np.ones((10,10))
print(x)
x[1:-1,1:-1] = 0
print('*********************************************************')
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
*********************************************************
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [45]:
x = np.ones((10,10))
#y = np.zeros((10,10))
print(x)
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print()
print()
print(x)
print()
print()
#print(y)
#y[1:-1,1:-1] = 1
#print()
#print(y)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [47]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [50]:
print(np.diag([1, 2, 3, 4, 5]))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [51]:
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [52]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [58]:
array = []
for i in range(8):
    array.append(list(np.tile([0,1],int(8/2))) if i%2==0 else list(np.tile([1,0],int(8/2))))
print(np.array(array))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [59]:
x= np.random.random((5,5))
print("Original")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("Normalized:")
print(x)

Original
[[0.47591852 0.40891732 0.98073526 0.51081394 0.44485439]
 [0.96063015 0.32382497 0.84069465 0.52429482 0.72099254]
 [0.97940775 0.15521817 0.99271267 0.34905017 0.75179035]
 [0.54877407 0.41086252 0.90747647 0.49442278 0.73989008]
 [0.49627755 0.21306202 0.99045323 0.70284819 0.58603628]]
Normalized:
[[0.3829283  0.30292635 0.98569851 0.42459475 0.34583656]
 [0.96169226 0.20132287 0.81848475 0.44069142 0.67555592]
 [0.98411342 0.         1.         0.23144272 0.71232966]
 [0.46992058 0.30524898 0.89822476 0.40502309 0.69812029]
 [0.40723775 0.06906773 0.99730214 0.65389088 0.51441306]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [61]:
#data = np.dtype([("r",np.ubyte, 1),("g",np.ubyte, 1),("b",np.ubyte, 1),("a",np.ubyte, 1)])
data = np.dtype([("r",np.ubyte),("g",np.ubyte),("b",np.ubyte),("a",np.ubyte)])
print(data)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [62]:
x = np.random.random((5,3))
print(x)
y = np.random.random((3,2))
print(y)
z = np.dot(x, y)
print("Dot product ")
print(z)

[[0.43176385 0.38081732 0.48394798]
 [0.15720079 0.3285011  0.57192548]
 [0.1781143  0.17910754 0.34615234]
 [0.15025931 0.67063585 0.87543589]
 [0.1784031  0.24358422 0.25930656]]
[[0.02308025 0.72155029]
 [0.6131459  0.10298606]
 [0.72628099 0.81701594]]
Dot product 
[[0.59494401 0.74615142]
 [0.62042594 0.61453155]
 [0.36533384 0.42977599]
 [1.05047808 0.89273087]
 [0.34179968 0.36567019]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [64]:
arr = np.arange(15)

arr[3:8] = np.multiply(arr[3:8],-1)

print(arr)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [66]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [69]:
#Z**Z # = [0^0, 1^1, 2^2] = [1, 1, 4]
#2 << Z >> 2  # = [0, 1, 2]
#Z < - Z      # = [False, False, False]
#1j * Z       # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
#Z / 1 / 1    # = [0, 1, 2]
#Z < Z > Z    # ValueError

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [73]:
#nan
#0
#array([-2.14748365e+09])


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [78]:
def round_array(x,y):
    return np.round(x,y)

test = np.array([32.11, 51.5, 0.112])
round_array(test,1)

array([32.1, 51.5,  0.1])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [80]:
array1 = np.array([0, 1, 2, 3, 4])
array2 = [1, 3, 4]
  
# Common values 
print(np.intersect1d(array1, array2))

[1 3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [82]:
data = np.random.random(1000).reshape(10, 10,10) * np.nan
np.seterr(all="ignore")
data

array([[[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]],

       [[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan,

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [83]:
np.sqrt(-1) == np.emath.sqrt(-1)
#false

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [84]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2021-11-20
Today:  2021-11-21
Tomorrow:  2021-11-22


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [85]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [87]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [88]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[2. 9. 2. 7. 3. 9. 5. 0. 8. 3.]
[2. 9. 2. 7. 3. 9. 5. 0. 8. 3.]
[2. 9. 2. 7. 3. 9. 5. 0. 8. 3.]
[2 9 2 7 3 9 5 0 8 3]
[2. 9. 2. 7. 3. 9. 5. 0. 8. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [100]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [101]:
def generate():
    for x in range(10):
        yield x
final = np.fromiter(generate(),dtype=float,count=-1)
print(final)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [102]:
x = np.random.random(10)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.0931123  0.34336761 0.26052824 0.22970551 0.25803224 0.00557489
 0.5266062  0.52483418 0.03853121 0.33036803]
Sorted array:
[0.00557489 0.03853121 0.0931123  0.22970551 0.25803224 0.26052824
 0.33036803 0.34336761 0.52483418 0.5266062 ]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [104]:
x = np.arange(10)
print(np.add.reduce(x))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [106]:
A = np.random.randint(0,3,8)
B = np.random.randint(0,3,8)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [109]:
x = np.zeros(4)
x.flags.writeable = False
#x[0] = 1
print(x)

[0. 0. 0. 0.]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [110]:
x = np.random.random((10,2))
X,Y = x[:,0], x[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.68006139 0.99068886 0.74065127 0.81158189 1.06531308 1.00642886
 0.84861262 0.87155492 1.02712806 0.60878721]
[1.28102326 0.30760257 1.43026911 1.44035091 0.87183101 0.19128107
 0.18115849 1.42438253 0.53022038 0.26142952]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [111]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.4188172  0.24405129 0.02633045 0.25960443 0.94664407 0.
 0.25446784 0.50199446 0.66810413 0.5134478 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [113]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [114]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [115]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [121]:
np.set_printoptions(threshold=np.sys.maxsize)
Z = np.zeros((8,8))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [122]:
x = np.arange(100)
y = np.random.uniform(0,100)
index = (np.abs(x-y)).argmin()
print(x[index])

26


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [124]:
x = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [127]:
import scipy
import scipy.spatial
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
Z = np.random.random((100,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.8556928  0.34718967 0.58513251 0.88422188 1.03304989
  0.58095229 0.21976949 0.85792228 0.60523252 1.06122657 1.00820618
  0.17232633 1.02564524 0.95850306 0.29543411 0.91405335 0.75774139
  0.9581732  1.04141603 0.50481352 0.35539196 1.03414836 1.02159062
  0.49653377 0.74263317 0.83663266 0.63254297 1.03932389 0.38271832
  0.8570161  0.4883191  0.99161491 0.44910125 1.07379216 0.77060082
  1.06903133 0.47062535 0.39144362 0.69841805 0.29348892 0.73454955
  0.26909043 0.98400233 0.57255861 0.60440087 0.71032626 0.86487773
  1.01761656 0.29421374 0.73754252 0.66413685 0.62390314 0.66899233
  0.71032787 0.86722592 1.18222657 0.85298792 0.34335717 0.46989253
  1.04004986 0.74247691 0.57824879 0.52164236 0.56674948 0.81310731
  0.01535682 0.78700808 0.83922666 0.45501773 0.59695558 0.79892693
  0.34060753 0.39460911 0.53657032 0.87394507 0.3772318  0.64764224
  0.54312122 0.18950904 0.54143829 0.85388132 0.42328937 0.14226553
  0.6644347  0.42686825 0.22355791 0.65664005 0.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [7]:
import numpy as np
x = np.arange(10, dtype=np.float32)
y = x.astype(np.int32, copy=False)
print(y)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [9]:
from io import StringIO
import numpy as np
s = StringIO(u"1, 2, 3, 4, 5,6,  ,  , 7, 8,  , 9,10,11")
data = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(data)

[ 1  2  3  4  5  6 -1 -1  7  8 -1  9 10 11]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [11]:
x = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(x):
    print(index, value)
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [12]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [13]:
n = 10
p = 3
x = np.zeros((n,n))
np.put(x, np.random.choice(range(n*n), p, replace=False),1)
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [14]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.15265959  0.19441859 -0.31428217  0.31964237 -0.36280366  0.31957722
  -0.40386871 -0.11547713  0.33401078  0.18144229]
 [ 0.34177715 -0.42750858 -0.12643989  0.39348012 -0.31808113  0.07409684
  -0.22476939  0.03903401  0.36519561 -0.11678475]
 [-0.33312975 -0.12091354 -0.18346918 -0.00286101  0.45986448  0.41556596
   0.14342177 -0.05507086 -0.20849096 -0.1149169 ]
 [ 0.3620789   0.29656159 -0.08947554 -0.06499885 -0.4030426  -0.18845751
   0.44714175 -0.0880948   0.16900359 -0.44071654]
 [ 0.04791691 -0.37709274 -0.12027648  0.24304992 -0.03763256  0.52423308
   0.25195728 -0.447502   -0.10831709  0.02366367]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [15]:
x = np.random.randint(0,10,(3,3))
print(x)
print(x[x[:,1].argsort()])

[[8 6 1]
 [0 6 7]
 [1 5 2]]
[[1 5 2]
 [8 6 1]
 [0 6 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [17]:
x = np.random.randint(0,3,(3,10))
print((~x.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [18]:
x = np.random.uniform(0,1,10)
y = 0.5
z = x.flat[np.abs(x - y).argmin()]
print(z)

0.4830159999062372


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [21]:
x = np.arange(3).reshape(3,1)
y = np.arange(3).reshape(1,3)
it = np.nditer([x,y,None])
for a,b,c in it: c[...] = a + b
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [23]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "test")
print (Z.name)

test


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [24]:
x = np.ones(10)
y = np.random.randint(0,len(x),20)
x += np.bincount(y, minlength=len(x))
print(x)
np.add.at(x, y, 1)
print(x)

[3. 4. 2. 2. 3. 2. 4. 4. 3. 3.]
[5. 7. 3. 3. 5. 3. 7. 7. 5. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [25]:
x = [1,2,3,4,5,6]
y = [1,3,9,3,4,1]
z = np.bincount(y,x)
print(z)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [26]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [27]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[58 57 50 53]
 [55 55 33 40]
 [65 31 66 45]]
[[58 57 50 53]
 [55 55 33 40]
 [65 31 66 45]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [28]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.36236739 0.51120298 0.67268153 0.46318993 0.59017245 0.42401153
 0.3829949  0.53371317 0.55959483 0.43875641]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [29]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([2.08868834, 1.75933773, 1.26201618, 1.39714707, 1.7619856 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [30]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [31]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [32]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [33]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 56) ( 1, 66) ( 3, 61) ( 3, 80) ( 8, 61) ( 8, 94) (10, 19) (10, 68)
 (13, 20) (13, 22) (13, 97) (19, 68) (20, 22) (22, 97) (33, 60) (33, 64)
 (51, 52) (51, 82) (52, 82) (56, 66) (57, 74) (57, 91) (60, 64) (61, 80)
 (61, 94) (71, 81) (71, 94) (74, 91) (81, 94)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [34]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [36]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
x = np.arange(20)
print(moving_average(x, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [37]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [38]:
x = np.random.randint(0,2,100)
np.logical_not(x, out=x)

x = np.random.uniform(-1.0,1.0,100)
np.negative(x, out=x)

array([-0.1961175 , -0.96722219,  0.85406909, -0.29646189, -0.8358108 ,
       -0.87329059, -0.7748204 , -0.16092399, -0.30591546,  0.16842329,
       -0.2785517 , -0.09359114, -0.90805309, -0.27101669,  0.62123093,
        0.57485606, -0.58034097, -0.52049991,  0.26407456, -0.32438541,
       -0.2382086 ,  0.3661916 , -0.44965794,  0.78048693, -0.25844934,
        0.26386919, -0.58014804, -0.09600883, -0.52883303,  0.48522052,
        0.34165315, -0.43692613,  0.9437383 , -0.68428689, -0.77983453,
        0.24785061,  0.85689127, -0.55625149,  0.42595142, -0.17711058,
        0.65501961,  0.79685401, -0.76693732,  0.36369578, -0.62359277,
        0.79631925, -0.15164567, -0.70470311,  0.3215124 ,  0.89524923,
        0.4200804 , -0.08954531, -0.66214343,  0.97993128,  0.65211607,
        0.84623792,  0.850807  ,  0.5624105 , -0.25069601, -0.30279323,
       -0.96521621,  0.61245988,  0.83873665, -0.72391045,  0.26953227,
        0.95997256,  0.88519169,  0.51753954, -0.77184831,  0.18

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [39]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.25141877  1.39197959 17.09142144  4.70104296  4.39366882  5.09048532
  7.04957085  1.49003903  7.92892087 10.328849  ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [40]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.11236798  6.0466865   4.45355123  3.4814691  11.39202988  5.56323854
   0.90281422  2.19276748  8.50328801  2.19836972]
 [ 1.6504      6.64399875  5.12373238  3.96647297 11.95457337  5.60848445
   0.2264307   2.60910681  9.10657482  1.95852598]
 [16.08551263  8.8195321   4.75194876  0.30952113  5.99074633 12.161659
  15.6225623  11.32285322  1.80102227 13.49080788]
 [ 3.21720096  9.56661495  0.53070381  3.03322378  5.64970497  2.30584342
   0.8560843   7.96765171  3.30327697  4.82145511]
 [ 3.90948314  3.20897602  0.06914254  0.25204268  7.33824632  4.10758388
   4.45579393  0.72134111  4.30202921  2.48283439]
 [10.04128433  4.30568133  7.39641906  5.20381831  1.37226079  4.53653067
  12.69199885  4.92404174  2.21361825  6.18811457]
 [ 5.98473345  3.01057001 15.16721837 15.13439699  8.02060071  4.89804775
  13.83482811  0.12958753 11.16403017  0.90103226]
 [10.11933347  3.49802583  4.36851615  2.02185843  4.57405061  6.79045319
  11.17720655  5.25627998  0.96180922  7.37486131]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [41]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[6 3 5 1 8 8 2 4 8 9]
 [3 6 3 0 4 5 9 8 7 9]
 [2 8 0 7 0 4 8 2 0 8]
 [8 7 5 9 6 1 1 9 4 7]
 [1 0 3 7 8 3 8 9 8 2]
 [7 1 6 0 6 2 3 0 7 7]
 [0 9 4 3 8 0 1 8 2 3]
 [7 6 6 5 3 9 5 6 2 7]
 [0 2 4 5 5 4 8 9 1 2]
 [6 9 1 4 6 8 7 4 7 7]]
[[0 0 0 0 0]
 [0 6 3 5 1]
 [0 3 6 3 0]
 [0 2 8 0 7]
 [0 8 7 5 9]]


C:\Users\lhris\AppData\Local\Temp/ipykernel_15980/1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [42]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [43]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [44]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [45]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 0 2]
   [2 4 2]
   [0 1 1]]

  [[0 2 3]
   [4 2 0]
   [1 1 4]]

  [[2 3 3]
   [2 0 3]
   [1 4 0]]

  [[3 3 4]
   [0 3 1]
   [4 0 4]]

  [[3 4 1]
   [3 1 1]
   [0 4 3]]

  [[4 1 0]
   [1 1 2]
   [4 3 4]]

  [[1 0 0]
   [1 2 4]
   [3 4 0]]

  [[0 0 3]
   [2 4 4]
   [4 0 3]]]


 [[[2 4 2]
   [0 1 1]
   [0 3 1]]

  [[4 2 0]
   [1 1 4]
   [3 1 0]]

  [[2 0 3]
   [1 4 0]
   [1 0 3]]

  [[0 3 1]
   [4 0 4]
   [0 3 1]]

  [[3 1 1]
   [0 4 3]
   [3 1 0]]

  [[1 1 2]
   [4 3 4]
   [1 0 0]]

  [[1 2 4]
   [3 4 0]
   [0 0 4]]

  [[2 4 4]
   [4 0 3]
   [0 4 0]]]


 [[[0 1 1]
   [0 3 1]
   [1 3 1]]

  [[1 1 4]
   [3 1 0]
   [3 1 4]]

  [[1 4 0]
   [1 0 3]
   [1 4 2]]

  [[4 0 4]
   [0 3 1]
   [4 2 0]]

  [[0 4 3]
   [3 1 0]
   [2 0 1]]

  [[4 3 4]
   [1 0 0]
   [0 1 2]]

  [[3 4 0]
   [0 0 4]
   [1 2 1]]

  [[4 0 3]
   [0 4 0]
   [2 1 4]]]


 [[[0 3 1]
   [1 3 1]
   [1 4 1]]

  [[3 1 0]
   [3 1 4]
   [4 1 1]]

  [[1 0 3]
   [1 4 2]
   [1 1 4]]

  [[0 3 1]
   [4 2 0]
   [1 4 0]]

  [[3 1 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [46]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7  6 11  2  6]
 [ 6  6  8 12  6]
 [11  8  6 42  6]
 [ 2 12 42  6  3]
 [ 6  6  6  3  0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [47]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [48]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [49]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [50]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])


[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [51]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [52]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [54]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 3 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [55]:
Z = np.random.randint(0,5,(10,3))
print(Z)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 0 0]
 [3 2 0]
 [4 2 4]
 [2 2 1]
 [2 2 2]
 [3 2 1]
 [4 0 4]
 [2 2 2]
 [0 4 0]
 [1 3 2]]
[[2 0 0]
 [3 2 0]
 [4 2 4]
 [2 2 1]
 [3 2 1]
 [4 0 4]
 [0 4 0]
 [1 3 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [56]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [58]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 1 0]]
[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [59]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)    

array([[0.14847335, 0.19850563, 0.71324532, 0.5853442 , 0.6624011 ,
        0.92899586, 0.37139523, 0.92258449, 0.945205  , 0.24396511],
       [0.11589545, 0.15494969, 0.55674564, 0.45690848, 0.51705762,
        0.72515638, 0.289904  , 0.72015178, 0.73780892, 0.19043449],
       [0.13131483, 0.17556506, 0.63081816, 0.51769811, 0.58584983,
        0.8216352 , 0.32847444, 0.81596477, 0.83597111, 0.21577095],
       [0.02378023, 0.03179365, 0.11423694, 0.09375165, 0.10609347,
        0.14879262, 0.05948452, 0.14776574, 0.15138876, 0.03907467],
       [0.09090945, 0.12154395, 0.43671636, 0.35840318, 0.40558471,
        0.56881928, 0.22740335, 0.56489363, 0.57874405, 0.14937855],
       [0.11332427, 0.15151208, 0.54439402, 0.44677179, 0.5055865 ,
        0.7090685 , 0.28347237, 0.70417494, 0.72144035, 0.18620963],
       [0.09777989, 0.13072957, 0.46972097, 0.38548931, 0.43623656,
        0.6118075 , 0.24458923, 0.60758517, 0.62248233, 0.16066776],
       [0.13883156, 0.18561477, 0.6669274

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [61]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [62]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [63]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.24422099  0.13089588]
